name = "personal-blog"
compatibility_date = "2026-09-30"
pages_build_output_dir = "public"

# After you run: npx wrangler d1 create personal-blog
# copy the database_id from the output into the line below.
[[d1_databases]]
binding = "DB"
database_name = "personal-blog"
database_id = "a351b6b3-c188-48b8-8ab6-6fcdaf2160b3"
